### ISSUE TITLE
Issue with "Preferences / Restore to Default"

### ISSUE THREAD

**Issue by TureBentzin** [monal-im/DebugTools#1]
I just found an issue with the LogViewer.

Pressing the "Restore Defaults" button causes the confirmation box to appear, but pressing "No" results in crash / close of the entire LogViewer application!
![grafik](https://github.com/monal-im/DebugTools/assets/38729194/18cee89c-51cd-4317-a806-046af5c463b3)
![grafik](https://github.com/monal-im/DebugTools/assets/38729194/9cab9f82-cb51-4677-9be7-491bf683a227)

That makes it very uncomfortable if you misclick on that button and then try to cancel the operation.

Also i would like to suggest a feature to toggle to a "dark" theme instead, so data can be read over a longer amount of time without hurting your eyesight. Currently i need to set all of the "background" colors for all log types by myself. But that works only to the point where a Querry results in less then an entire page of results. The empty space is then white.
![grafik](https://github.com/monal-im/DebugTools/assets/38729194/46dbebd6-7758-490e-ae53-d16c2a478e85)

**Comment by tmolitor-stud-tu** [comment]
For the dark theme: pull requests are always welcome :)

**Comment by tmolitor-stud-tu** [comment]
May I ask why you plan to spend several hours reading log files from Monal?

**Comment by TureBentzin** [comment]
Very good. Thank you for addressing suggestions!
