### ISSUE TITLE
[MLV] Handle `Pos1` and `End` keys

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [monal-im/DebugTools#3]
`STRG+Pos1` and `STRG+End` should jump to the first/last visible logline.

`Pos1` and `End` should either do the same or jump to the first/last logline in the current viewport.

Both should only trigger if the logview is currently focused, not when the focus is in any of the textviews.

**Comment by Sobottasgithub** [comment]
Implemented in this commit: e0c049eb429e54aff555a49a8aa2be3f39ab2f5f
