### ISSUE TITLE
Pressing `DOWN` arrow should not jump over the first selectbox entry

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [monal-im/DebugTools#4]
The title says it all, maybe add an empty entry to the top of the filter and search selectboxes to be jumped over.
But don't add this empty entry to the history.

**Comment by tmolitor-stud-tu** [comment]
> But don't add this empty entry to the history.
this is not solved yet

**Comment by Sobottasgithub** [comment]
Should have been fixed in this commit: 4cbbdc3
